#!/bin/bash
pip3 install --user grpcio-tools
go get github.com/BurntSushi/toml gopkg.in/mgo.v2 github.com/gorilla/mux
go get google.golang.org/grpc
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
mongo edraj --eval 'db.content.drop();'
mongorestore --gzip --dir ../sample_data/dump/
mongo edraj --eval 'db.content.count();'
mongo edraj --eval 'db.content.getIndices();'
#mongo edraj --eval 'db.content.createIndex( { displayname: "text", body: "text" }, {"default_language":"none"} );' #  Arabic sadly requires 3rd party license
