#!/bin/bash
pip3 install --user grpcio-tools
go get github.com/BurntSushi/toml gopkg.in/mgo.v2 github.com/gorilla/mux
go get google.golang.org/grpc
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
mongo edraj --eval 'db.content.drop();'
mongorestore -d edraj -c content --gzip --dir ../sample_data/dump/edraj/content.bson.gz
mongo edraj --eval 'db.content.count();'
